export const historicalFacts = [
    "In 1007, Viking explorer Thorfinn Karlsefni attempted to establish a permanent colony in North America, but abandoned it after his son Snorri—the first European born in America—was just three years old.",
    "The Byzantine Emperor Basil II was so brutal to the Bulgarians in 1014 that he blinded 99 out of every 100 prisoners, leaving one man in each group with one eye to lead the others home.",
    "In 1066, King Harold II fought two major battles just three weeks apart—defeating the Vikings at Stamford Bridge, then marching 250 miles south to face William the Conqueror at Hastings.",
    "The medieval city of Cahokia, near modern St. Louis, had a population of around 20,000 in 1100 CE—larger than London at the time.",
    "During the Siege of Château Gaillard in 1204, French soldiers entered the castle through the unguarded toilet chute.",
    "Genghis Khan killed so many people (an estimated 40 million) that it actually cooled the Earth's climate by allowing forests to regrow on abandoned farmland.",
    "In 1241, the Mongols defeated two European armies within two days of each other, 300 miles apart—a feat of coordinated warfare not matched until the 20th century.",
    "Frederick II, Holy Roman Emperor, conducted a famous experiment where children were raised without any spoken language to discover humanity's 'natural tongue.' The children all died.",
    "The medieval Catholic Church held trials against animals, including a 1386 case where a pig was dressed in human clothes, tried for murder, and publicly executed.",
    "In 1347, the Black Death arrived in Europe via twelve Genoese trading ships at the Sicilian port of Messina—most of the sailors aboard were already dead.",
    "The Aztec capital Tenochtitlan had a population of 200,000 in 1500, making it one of the largest cities in the world—five times larger than contemporary London.",
    "When Hernán Cortés arrived in Mexico in 1519, the Aztecs initially thought he might be the returning god Quetzalcoatl because he arrived in the exact year predicted by their calendar.",
    "Henry VIII's suit of armor, still preserved in the Tower of London, shows his waist expanded from 32 inches to 54 inches over his lifetime.",
    "In 1527, a group of unpaid Imperial soldiers sacked Rome so thoroughly that the Pope had to escape through a secret corridor to Castel Sant'Angelo while Swiss Guards died defending him.",
    "Ivan the Terrible killed his own son and heir with a blow to the head during an argument in 1581, ensuring the eventual end of the Rurik dynasty.",
    "Queen Elizabeth I owned over 2,000 dresses, yet bathed only once a month 'whether she needed it or not'—which was considered excessive cleanliness for the era.",
    "In 1588, more Spanish Armada ships were destroyed by storms off the coasts of Scotland and Ireland than by English cannons.",
    "Tokugawa Ieyasu won the Battle of Sekigahara in 1600 partly because several 'allies' of his opponent had secretly agreed to defect or do nothing.",
    "The Thirty Years' War (1618-1648) killed approximately one-third of the German population—a higher percentage than either World War.",
    "In 1648, angry Parisians stormed the royal palace during the Fronde rebellion; young King Louis XIV never forgot this humiliation and eventually built Versailles partly to escape Paris.",
    "Coffee was banned in Mecca in 1511, in Constantinople in 1623, and in England in 1675—always for fear it encouraged seditious talk.",
    "During the Great Fire of London in 1666, Samuel Pepys buried his Parmesan cheese in his garden to save it from the flames.",
    "The last dodo was killed around 1681, but the bird was so poorly documented that scientists later questioned whether it had ever existed at all.",
    "In 1685, the Monmouth Rebellion failed partly because the Duke of Monmouth's supporters in London learned of his landing via an early newsletter—the authorities read the same paper.",
    "Peter the Great of Russia was 6'8\" tall, but would hide under tables during thunderstorms because of his severe phobia.",
    "The South Sea Bubble of 1720 was so catastrophic that Parliament debated punishing the directors by sewing them into sacks with snakes and throwing them into the Thames.",
    "In 1739, Britain declared war on Spain partly because of public outrage over Captain Robert Jenkins, who displayed his severed ear (allegedly cut off by Spanish coast guards) to Parliament.",
    "Frederick the Great of Prussia wrote his military orders in French because he considered German too crude for sophisticated communication.",
    "During the Battle of Fontenoy in 1745, British and French officers reportedly bowed to each other and argued over who should fire first.",
    "The Library of Congress notes that Benjamin Franklin proposed the turkey as America's national bird, calling the bald eagle 'a bird of bad moral character.'",
    "Catherine the Great of Russia personally corresponded with Voltaire and Diderot, and bought Diderot's library just to let him keep using it.",
    "In 1770, five colonists were killed in the Boston Massacre; their defense lawyer was John Adams, future President, who won acquittal for most of the soldiers.",
    "Marie Antoinette never said 'let them eat cake'—the phrase appeared in Rousseau's writing when she was only nine years old.",
    "During the French Revolution, the guillotine was considered a humanitarian advancement because it killed quickly and equally, regardless of social class.",
    "Napoleon's troops in Egypt in 1799 used the Sphinx for target practice, destroying its nose (though this is disputed—drawings from before Napoleon show it already missing).",
    "The Haitian Revolution (1791-1804) was the only successful slave revolt that created a nation, defeating the armies of Spain, Britain, and Napoleon's France.",
    "In 1804, Aaron Burr killed Alexander Hamilton in a duel, then fled to the Western frontier where he allegedly plotted to create his own country.",
    "Napoleon escaped from Elba in 1815 with just 1,000 men but reached Paris without firing a shot—regiment after regiment defected to him.",
    "The eruption of Mount Tambora in 1815 caused 'the year without a summer' in 1816, leading Mary Shelley to write Frankenstein while trapped indoors.",
    "Simón Bolívar liberated six countries from Spanish rule but died virtually penniless, saying 'all who served the revolution have plowed the sea.'",
    "In 1838, the Cherokee Nation was forced to walk 1,000 miles in the Trail of Tears; their word for the path translates to 'the trail where they cried.'",
    "Charles Darwin and Abraham Lincoln were born on the exact same day: February 12, 1809.",
    "The Great Stink of 1858 was so foul that Parliament hung sheets soaked in chloride of lime over the windows and debated moving to Oxford.",
    "During the American Civil War, 2% of the entire US population died—the equivalent of 6 million people today.",
    "In 1867, the United States purchased Alaska from Russia for $7.2 million—about 2 cents per acre—and newspapers called it 'Seward's Folly.'",
    "The Paris Commune of 1871 lasted only 72 days but saw working-class Parisians establish the first elected workers' government in history.",
    "During the Siege of Paris in 1870-71, Parisians ate the zoo animals, including the beloved elephants Castor and Pollux.",
    "In 1876, just hours before Custer's Last Stand, many of his soldiers had been drinking and playing baseball at Fort Lincoln.",
    "The Emu War of 1932 saw the Australian military deploy Lewis guns against emus destroying crops—the emus won.",
    "Jack the Ripper killed five women in 1888 Whitechapel; the case generated so many letters to police that they invented modern profiling to sort through them.",
    "In 1893, New Zealand became the first self-governing country where women could vote—29 years before the United States.",
    "The Dreyfus Affair (1894-1906) tore France apart over antisemitism and military corruption, dividing families and ending friendships for a generation.",
    "During the Boxer Rebellion in 1900, the eight-nation alliance that invaded China included rivals Japan and Russia fighting side by side.",
    "Archduke Franz Ferdinand's driver made a wrong turn in 1914, stopping directly in front of Gavrilo Princip, who had given up on the assassination and was eating a sandwich.",
    "The Christmas Truce of 1914 saw German and British soldiers play football in no man's land; the generals were furious and ensured it never happened again.",
    "More soldiers died from the Spanish Flu pandemic in 1918 than from combat in World War I.",
    "In 1917, the Germans sent Lenin to Russia in a sealed train, hoping he would destabilize their enemy—it worked far better than they expected.",
    "The Sykes-Picot Agreement of 1916, in which Britain and France secretly divided the Middle East between them, still shapes regional conflicts today.",
    "Al Capone's business card said he was a used furniture dealer; at his peak, he earned an estimated $100 million per year from bootlegging.",
    "In 1923, German hyperinflation was so severe that workers were paid twice daily so they could spend their money before it became worthless.",
    "The Wall Street Crash of 1929 wiped out $30 billion in stock value within days—roughly equal to the entire cost of American involvement in WWI.",
    "In 1936, Jesse Owens won four gold medals at the Berlin Olympics; Hitler refused to shake his hand, but FDR never invited him to the White House either.",
    "The Hindenburg disaster in 1937 killed 36 people and was captured on film—effectively ending the era of passenger airships.",
    "During the 1936-39 Spanish Civil War, George Orwell was shot through the throat by a fascist sniper but survived to write Homage to Catalonia.",
    "Winston Churchill was 65 years old and considered a political failure when he became Prime Minister in May 1940.",
    "In 1940, radar operators detected the incoming Japanese attack on Pearl Harbor but their warning was dismissed as a flight of American B-17 bombers.",
    "During the Siege of Leningrad (1941-44), over a million civilians starved to death—survivors reported the city fell silent because there were no birds, cats, or dogs left.",
    "The entire Polish government-in-exile's intelligence network was run from a flat in London, helping crack Enigma and coordinate the Warsaw Uprising.",
    "More people died in the firebombing of Tokyo on March 9, 1945 (over 100,000) than in the immediate aftermath of either atomic bomb.",
    "In 1945, Japan's war council deadlocked on surrender even after two atomic bombs; Emperor Hirohito broke the tie in history's most consequential casting vote.",
    "The Nuremberg Trials established that 'I was just following orders' was not a valid defense for war crimes—a legal principle still cited today.",
    "The Marshall Plan invested $13 billion ($150 billion today) into rebuilding Europe, including former enemy Germany.",
    "In 1947, when India was partitioned, the new borders weren't announced until after independence, causing 15 million people to suddenly find themselves in the 'wrong' country.",
    "The Berlin Airlift (1948-49) delivered 2.3 million tons of supplies, with planes landing every 30 seconds at the peak.",
    "Mao Zedong's Great Leap Forward (1958-62) caused a famine that killed between 30-45 million people—the deadliest in human history.",
    "In 1960, four Black college students sat at a whites-only Woolworth's lunch counter in Greensboro and refused to leave—within weeks, sit-ins spread to 55 cities.",
    "The Bay of Pigs invasion in 1961 failed partly because CIA planners had looked at a map and saw swamps but hadn't realized they were full of sharp coral.",
    "During the Cuban Missile Crisis in 1962, a Soviet submarine commander voted against launching a nuclear torpedo; two other officers had already approved.",
    "The Great Train Robbery of 1963 netted £2.6 million (over £50 million today) and made celebrities of the robbers.",
    "In 1963, Buddhist monk Thích Quảng Đức burned himself to death in Saigon to protest the persecution of Buddhists; he didn't move or make a sound.",
    "Malcolm X was assassinated in 1965 by members of the Nation of Islam; three men were convicted, but two were exonerated in 2021.",
    "The Six-Day War of 1967 was so swift that Israel captured the Sinai, West Bank, Gaza Strip, and Golan Heights in less than a week.",
    "In 1968, the Prague Spring was crushed by 200,000 Warsaw Pact troops; one student, Jan Palach, burned himself to death in protest.",
    "The Troubles in Northern Ireland (1968-1998) killed over 3,500 people in a country smaller than Connecticut.",
    "Apollo 11's lunar module computer crashed multiple times during descent; Armstrong had to land manually with about 25 seconds of fuel remaining.",
    "The Watergate break-in in 1972 was discovered because a security guard noticed tape on a door latch—placed there by the burglars to prevent it from locking.",
    "In 1973, Salvador Allende died during a military coup in Chile; his final radio address ended mid-sentence as jets bombed the presidential palace.",
    "The Khmer Rouge's reign in Cambodia (1975-79) killed nearly 2 million people—about 25% of the country's population.",
    "In 1979, Iran's revolution happened so fast that the CIA station chief was still sending cables assuring Washington that the Shah was secure.",
    "During the Soviet invasion of Afghanistan (1979-89), the US supplied Stinger missiles to the mujahideen—weapons that later turned up in conflicts worldwide.",
    "In 1981, Pope John Paul II was shot four times in St. Peter's Square but survived; he later visited and forgave his would-be assassin in prison.",
    "The Falklands War of 1982 saw Britain send a naval task force 8,000 miles to recapture islands with fewer than 2,000 residents.",
    "In 1984, Indira Gandhi was assassinated by her own Sikh bodyguards in retaliation for ordering an attack on the Golden Temple; anti-Sikh riots killed thousands.",
    "The Chernobyl disaster in 1986 released 400 times more radiation than the Hiroshima bomb; the effects are still visible in elevated cancer rates.",
    "In 1989, a lone man stood in front of a column of tanks in Tiananmen Square; his identity and fate remain unknown.",
    "The fall of the Berlin Wall on November 9, 1989 happened partly by accident—an East German spokesman mistakenly announced the border was 'immediately' open.",
    "Nelson Mandela was released in 1990 after 27 years in prison; he forgave his captors and invited his former jailer to his presidential inauguration.",
    "The Gulf War in 1991 was the first conflict broadcast live on television; viewers watched missiles strike Baghdad in real time.",
    "The Rwandan Genocide of 1994 killed approximately 800,000 Tutsis in just 100 days—a faster rate of killing than the Holocaust.",
    "In 1995, the Srebrenica massacre saw Bosnian Serb forces murder over 8,000 Bosniak men and boys under the eyes of UN peacekeepers.",
    "The Handover of Hong Kong in 1997 saw the British flag lowered for the last time over a territory that had been a colony for 156 years.",
    "The Good Friday Agreement of 1998 ended 30 years of conflict in Northern Ireland; it passed with 71% support in a referendum.",
    "In 1999, NATO bombed Serbia for 78 days to stop ethnic cleansing in Kosovo—the first war fought entirely from the air.",
    "The Y2K bug caused worldwide panic but few actual problems, thanks to an estimated $300 billion spent fixing it.",
    "In 1184, the German city of Erfurt hosted a meeting in a monastery latrine; the floor collapsed, plunging dozens of nobles into the cesspit below.",
    "In 1346 at the Battle of Crécy, English longbowmen defeated French knights partly because it had just rained and crossbows got wet and useless.",
    "In 1252, the Mongols deployed early gunpowder bombs—described by witnesses as 'thunder crash bombs'—against walled cities in China.",
    "In 1518, Strasbourg experienced a 'dancing plague' where hundreds danced uncontrollably for days; some reportedly died from exhaustion.",
    "In 897, Pope Formosus was put on trial as a corpse; the Cadaver Synod literally propped him on a throne to condemn him.",
    "In 1483, the Spanish Inquisition published a manual for detecting false repentance; it unintentionally became a bestseller.",
    "The Knights Templar, dissolved in 1312, owned most of the best vineyards in France and pioneered some early banking systems.",
    "In 1167, London suffered a heatwave so intense that chroniclers wrote of fish dying in the Thames mid-swim.",
    "In 1381, during the Peasants’ Revolt, rebel leader Wat Tyler demanded the abolition of serfdom centuries before it happened.",
    "In 1626, Dutch governor Peter Minuit purchased Manhattan for goods worth roughly $1,000 in today’s money.",
    "In 1667, the Dutch raided the River Thames and stole the English flagship HMS Royal Charles; its stern plate is still in Amsterdam.",
    "In 1212, thousands of children in Europe attempted a crusade to the Holy Land; none reached it, and many disappeared.",
    "In 1637, tulip bulbs briefly became so valuable in the Netherlands that one bulb sold for more than a craftsman earned in 10 years.",
    "In 1360, a hailstorm killed more than 1,000 English soldiers during a temporary truce in the Hundred Years' War.",
    "In 1232, the Song Dynasty used rockets in battle—fire arrows propelled by gunpowder—centuries before Europe caught up.",
    "In 1783, the Icelandic Laki eruption released enough sulfur to cause crop failures across Europe, contributing to pre-revolutionary unrest.",
    "In 1714, the British government offered £20,000 (millions today) for a method to calculate longitude; a carpenter solved it with a clock.",
    "In 1815, the Tambora eruption triggered the 'Year Without a Summer', causing frost in New England in July and inspiring Mary Shelley's Frankenstein.",
    "In 1002, King Æthelred ordered the massacre of Danes in England; this helped spark renewed Viking invasions.",
    "In 1325, two Italian city-states—Modena and Bologna—fought a war over a stolen wooden bucket.",
    "In 1521, Ferdinand Magellan tried to convert a Pacific island by force and was killed by local warriors in minutes.",
    "In 1429, teenage Joan of Arc lifted the siege of Orléans and transformed the Hundred Years’ War within nine days.",
    "In 1600, Japan’s Battle of Sekigahara involved more than 150,000 troops and created 250 years of stability under the Tokugawa shogunate.",
    "In 1665, during London's plague, Isaac Newton fled to the countryside and invented calculus and foundational optics.",
    "In 1686, the Mughal Emperor Aurangzeb built a chain of over 100 toll posts purely to stop people drinking alcohol.",
    "In 1777, Vermont briefly operated as an independent republic, with its own currency and foreign policy, before joining the U.S.",
    "In 1789, the French National Assembly abolished feudalism in one night—noble privileges that had existed for 800 years vanished instantly.",
    "In 1854, Florence Nightingale transformed battlefield medicine during the Crimean War, reducing death rates from 42% to 2%.",
    "In 1814, Washington D.C. was burned by British troops, who enjoyed a dinner in the White House before torching it.",
    "In 1649, after Charles I was executed, England briefly became a republic run by a general and enforced by the world's first state navy.",
    "In 1367, the Ottoman Empire nearly ended in infancy when a single battle left only one surviving heir.",
    "In 1917, Russia’s 'February Revolution' happened in March, and its 'October Revolution' in November, thanks to the Julian calendar.",
    "In 1921, Adolf Hitler and his early followers brawled with political opponents in Munich beer halls long before he was widely known.",
    "In 1940, British codebreakers at Bletchley Park solved Italian naval ciphers and helped win the Mediterranean campaign.",
    "In 1692, the Salem Witch Trials accepted 'spectral evidence': testimony about visions and dreams.",
    "In 1588, the Spanish Armada was largely destroyed not by combat but by storms the English called 'Protestant winds'.",
    "In 1494, a single monk in Florence invented double-entry bookkeeping, reshaping global commerce.",
    "In 1431, Korean admiral Yi Sun-sin developed ironclad ‘turtle ships’, centuries before European equivalents.",
    "In 1794, the French revolutionaries replaced the traditional calendar with a decimal one featuring 10-day weeks.",
    "In 1867, the U.S. purchased Alaska from Russia for $7.2 million; it was mocked as 'Seward’s Folly'.",
    "In 1453, the fall of Constantinople used the largest cannon ever built to that date; it required 60 oxen to move.",
    "In 1780, a strange daytime darkness fell across New England; scientists now think it was a massive wildfire in Canada.",
    "In 1883, Krakatoa's eruption was heard 3,000 miles away and altered global sunsets for years.",
    "In 1364, the University of Kraków was founded and later became home to Copernicus.",
    "In 1420, China built the Forbidden City using more than a million laborers over 14 years.",
    "In 1297, the Swiss used a hedgehog-like infantry formation to defeat the Habsburg cavalry at Morgarten.",
    "In 1697, Peter the Great toured Europe incognito to learn shipbuilding, even working in Dutch shipyards.",
    "In 1575, the Battle of Nagashino saw Japan's first large-scale use of coordinated gunfire.",
    "In 1132, monks in northern China described the first known gunpowder factory accident.",
    "In 1803, Napoleon sold the Louisiana Territory to the U.S. to fund a war he ultimately lost.",
    "In 1712, Russian Tsar Peter I instituted a beard tax; clean-shaven faces were a symbol of modernization.",
    "In 1402, Timur the Lame defeated the Ottoman Sultan Bayezid, who subsequently died in captivity.",
    "In 1602, the Dutch East India Company became the first publicly traded corporation.",
    "In 1511, the Portuguese empire captured Malacca, opening Europe to the spice trade's center.",
    "In 1633, Galileo was forced to recant his support of heliocentrism under threat of torture.",
    "In 1791, Haiti began the only successful slave revolt in history, founding the first Black republic.",
    "In 1916, Rasputin survived cyanide, multiple stabbings, a shooting, and possibly drowning before dying.",
    "In 1526, the Battle of Mohács erased Hungary as an independent power for centuries.",
    "In 1770, Captain Cook first charted Australia's east coast, claiming it for Britain.",
    "In 1648, the Thirty Years’ War ended, killing an estimated one-third of Germany’s population.",
    "In 1571, the Battle of Lepanto halted Ottoman expansion into the western Mediterranean.",
    "In 1911, Roald Amundsen reached the South Pole beating Robert Falcon Scott by five weeks.",
    "In 1860, Abraham Lincoln won the presidency with under 40% of the vote in a four-way race.",
    "In 1859, Darwin published On the Origin of Species, rewriting humanity’s self-understanding.",
    "In 1492, the Alhambra Decree expelled Jews from Spain after centuries of flourishing scholarship.",
    "In 1662, the Royal Society began publishing Philosophical Transactions, the first scientific journal.",
    "In 1905, Einstein’s 'miracle year' produced four breakthroughs, including the E=mc² paper.",
    "In 1434, Cosimo de’ Medici returned from exile and effectively ruled Florence without a title.",
    "In 1918, the Spanish Flu killed more people than World War I in just two years.",
    "In 1798, the Irish Rebellion saw the last major attempt to break free from British rule before 1916.",
    "In 1767, the Jesuits were expelled from every territory of the Spanish Empire in a single coordinated decree.",
    "In 1352, Venetian merchants were trading slaves in the Crimea; one of them introduced the plague to the Mediterranean.",
    "In 1589, Henry IV survived an assassination attempt because his attacker’s knife got stuck in thick clothing.",
    "In 1922, Howard Carter opened Tutankhamun’s tomb, sparking global Egyptomania.",
    "In 1066, King Harold was hit in the eye with an arrow during the Battle of Hastings—probably.",
    "In 1680, Pueblo peoples in the American Southwest coordinated a rebellion using knotted cords as a calendar.",
    "In 1703, Russia founded St. Petersburg on a swamp; within a decade it rivaled Amsterdam in scale.",
    "In 1807, Britain abolished the transatlantic slave trade, though slavery itself persisted into the 1830s.",
    "In 1866, the grand army of Liechtenstein went to war with 80 men and returned with 81, having made a friend along the way.",
    "Oxford University (teaching since 1096) is older than the Aztec Empire (began 1428).",
    "Hitler, Stalin, Trotsky, Tito, and Freud all lived in Vienna in 1913, frequently frequenting the same coffeehouses.",
    "The 'Dancing Plague' of 1518 saw hundreds of people in Strasbourg dance uncontrollably for days, many dying of exhaustion.",
    "Nintendo was founded in 1889, meaning the company is older than the Eiffel Tower and existed while the Ottoman Empire was still a world power.",
    "The last samurai fought in 1877; the fax machine was patented in 1843. A samurai could have technically faxed Abraham Lincoln.",
    "In 1184, arguably the worst structural failure in medieval history occurred at Erfurt Cathedral when the floor collapsed during a meeting, causing 60 nobles to fall into the latrine below and drown in liquid excrement.",
    "Pepsi briefly owned the 6th largest navy in the world in 1989 after the USSR traded warships for soda.",
    "Harvard University (founded 1636) was established before Isaac Newton published the laws of motion and gravity.",
    "The 1904 Olympic Marathon in St. Louis featured a runner chased off course by wild dogs, another who napped mid-race, and a winner who was carried across the line hallucinating from rat poison and brandy.",
    "King Charles VI of France (r. 1380–1422) suffered from 'glass delusion,' believing he was made of glass and would shatter if touched.",
    "The 'Kettle War' of 1784 between the Netherlands and the Holy Roman Empire ended after a single shot hit a soup kettle.",
    "Lord Byron kept a pet bear in his dormitory at Cambridge because the university statutes forbade keeping dogs.",
    "During the Victorian era, people used 'Mummy Brown' paint, which was made from ground-up ancient Egyptian mummies.",
    "The shortest war in history was not just short; the Sultan of Zanzibar's palace was destroyed by the British in 38 minutes in 1896 because he refused to step down.",
    "In 1967, Australian Prime Minister Harold Holt went for a swim at the beach and was never seen again.",
    "Before dentures were synthetic, 18th and 19th-century 'Waterloo Teeth' were dentures made from the teeth of tens of thousands of dead soldiers scavenged from battlefields.",
    "The Great Emu War of 1932 saw the Australian military fight a flock of 20,000 emus using machine guns. The emus won.",
    "Victor Lustig, a con artist, successfully 'sold' the Eiffel Tower for scrap metal—twice.",
    "Pope Gregory IX (1227–1241) declared cats to be instruments of Satan, leading to mass killings of cats which likely exacerbated the Black Death by increasing the rat population.",
    "The 1814 London Beer Flood killed eight people when a vat containing 135,000 gallons of porter ruptured.",
    "When the Mona Lisa was stolen from the Louvre in 1911, more people visited the museum to stare at the empty wall than had ever viewed the painting itself.",
    "Tsutomu Yamaguchi happened to be in Hiroshima on business when the first atomic bomb dropped, survived, took a train home to Nagasaki, and arrived just in time for the second bomb. He survived both.",
    "General Santa Anna of Mexico held a full state funeral for his amputated leg in 1842.",
    "During the Cold War, the CIA spent $20 million on 'Acoustic Kitty,' a project to equip cats with microphones. On the first field test, the cat was immediately run over by a taxi.",
    "President Andrew Jackson's pet parrot had to be removed from Jackson's funeral because it wouldn't stop screaming profanities.",
    "The 'year without a summer' (1816), caused by the eruption of Mount Tambora, kept Mary Shelley indoors where she wrote Frankenstein.",
    "The jagged border between the US and Canada in Minnesota exists because mapmakers in 1783 relied on a map that depicted a non-existent island in Lake Superior.",
    "Waiters in 11th-century Venice were shocked when a Byzantine princess used a golden fork to eat; the church condemned it as 'excessive delicacy' when God gave humans fingers.",
    "From 1912 to 1948, the Olympic Games awarded medals for painting, sculpture, architecture, literature, and music.",
    "In 1976, the US and South Korea launched 'Operation Paul Bunyan,' sending an aircraft carrier task force, B-52 bombers, and F-111 jets just to cut down a single poplar tree in the DMZ.",
    "Thomas Jefferson and John Adams, the only two signatories of the Declaration of Independence who became presidents, both died on July 4, 1826—the 50th anniversary of the Declaration.",
    "Heroin was originally marketed by Bayer in 1898 as a 'non-addictive' cough medicine for children.",
    "The first person to survive a trip over Niagara Falls in a barrel was a 63-year-old schoolteacher named Annie Edson Taylor in 1901.",
    "During the siege of Tenochtitlan (1521), the conquistadors built a trebuchet to save gunpowder, but it immediately fired a projectile straight up, which came back down and destroyed the machine.",
    "Charlie Chaplin once entered a 'Charlie Chaplin look-alike contest' in Monte Carlo and came in 20th place (or 3rd, depending on the account, but he certainly didn't win).",
    "In 1726, a woman named Mary Toft convinced doctors, including the Surgeon to the King, that she had given birth to rabbits.",
    "Within hours of the Titanic sinking in 1912, The New York Times had the story, but the Daily Mail ran the headline 'Titanic Sunk, No Lives Lost'.",
    "Tulip Mania in the Netherlands (1637) saw the price of a single tulip bulb rise to exceed the cost of a luxury home.",
    "Cornflakes were invented by John Harvey Kellogg as part of a bland diet intended to suppress sexual desire and prevent masturbation.",
    "In 1956, a man named Tommy Fitzpatrick stole a plane from New Jersey and landed it on a street in New York City on a bet. Two years later, he did it again because someone at a bar didn't believe him.",
    "The 'War of Jenkins' Ear' (1739) between Britain and Spain was ostensibly started because a British captain had his ear cut off by the Spanish coast guard.",
    "Ivan the Terrible (1530–1584) beat his own son and heir to death during an argument, effectively ending his dynasty and leading to the Time of Troubles.",
    "Napoleon Bonaparte was attacked by a horde of rabbits during a hunting trip he had organized; the rabbits were domesticated and saw him as a food provider rather than a hunter.",
    "Calculus was invented (late 17th century) after the founding of Harvard (1636).",
    "Only 66 years passed between the first powered flight by the Wright Brothers (1903) and the Moon landing (1969). Orville Wright lived to see the sonic barrier broken.",
    "The Maginot Line, France's impenetrable WWII defense, had AC and underground trains, but the Germans simply drove around it through Belgium.",
    "Russia was still using the Julian calendar in 1908, so their Olympic team arrived in London 12 days late for the games.",
    "Salvador Dalí would often avoid paying restaurant tabs by drawing on the back of the check, knowing the owner would never cash such a valuable piece of art.",
    "Until the mid-20th century, cigarette brands like Camel were promoted by doctors as good for throat health.",
    "The 'Cadaver Synod' (897 AD, just before your cutoff but relevant context) involved putting a dead Pope on trial, but in the 1400s, posthumous execution remained a legal practice.",
    "Empress Cixi of China (1835–1908) used funds intended for the modernization of the Chinese navy to build a marble boat for her summer palace. The marble boat did not float.",
    "In 1982, a man named Larry Walters attached 45 weather balloons to a lawn chair and floated into LAX airspace at 16,000 feet.",
    "The crew of Apollo 11 had to fill out customs declaration forms upon returning to Earth, declaring 'moon rock and moon dust samples'.",
    "The 1859 'Pig War' between the US and Britain was a boundary dispute in the San Juan Islands triggered by an American farmer shooting a British pig.",
    "Ancient Roman concrete is chemically superior to modern concrete in terms of longevity, getting stronger over time due to seawater reaction, a recipe lost for over 1000 years.",
    "When the tomb of King Casimir IV of Poland was opened in 1973, 10 of the 12 researchers died shortly after, fueling 'curse' rumors similar to Tutankhamun (likely fungal spores).",
    "Genghis Khan killed so many people (approx. 40 million) that the Earth's carbon levels dropped because farmland returned to forest, effectively cooling the planet.",
    "Historically, the color pink was considered masculine (a watered-down red) and blue was feminine (delicate and associated with the Virgin Mary) until the mid-20th century.",
    "The US government poisoned alcohol during Prohibition (1920s-30s) to discourage drinking, resulting in an estimated 10,000 deaths.",
    "Benjamin Franklin never actually proposed the turkey as the national bird, but he did write a letter to his daughter criticizing the bald eagle as a 'bird of bad moral character'.",
    "During the Siege of Paris (1870), starving citizens ate the animals in the zoo, including Castor and Pollux, the two popular elephants.",
    "High heels were originally worn by Persian cavalrymen (10th century onwards) to help keep their boots in stirrups, before becoming fashion for European male aristocrats.",
    "A 1908 car race from New York to Paris involved the German team shipping their car part of the way, the American team driving on railroad tracks, and the race taking nearly six months.",
    "During WWII, the US military developed a 'Bat Bomb'—a casing containing hibernating bats with time-delayed incendiary devices attached, intended to burn down Japanese cities.",
    "Captain Cook did not 'discover' Australia; he was beaten there by the Dutch explorer Willem Janszoon by over 160 years (1606), who thought it was a swampy mess and left.",
    "New Zealand was the first self-governing country to grant women the right to vote in 1893.",
    "Volvo invented the three-point seatbelt in 1959 and gave the patent away for free to save lives.",
    "In 1999, Google's founders tried to sell the company to Excite for $1 million (later reduced to $750,000). The Excite CEO refused.",
    "The Great Smog of London in 1952 killed up to 12,000 people and led to the Clean Air Act.",
    "Prussian King Frederick William I (1688–1740) had a regiment of 'Potsdam Giants'—he would trade diamonds for extremely tall men and even attempted to breed them.",
    "Fidel Castro survived an estimated 638 assassination attempts, including exploding cigars and a poisoned wetsuit.",
    "The 'Defenestration of Prague' in 1618, which started the Thirty Years' War, involved Protestant rebels throwing Catholic officials out of a window. They survived by landing in a pile of manure.",
    "Queen Victoria survived at least seven assassination attempts during her reign.",
    "While constructing the Trans-Siberian Railway, workers had to fight off tigers.",
    "Switzerland has accidentally invaded Liechtenstein three times in modern history (mostly due to soldiers getting lost in the woods).",
    "The last person to be executed by guillotine in France was Hamida Djandoubi in September 1977.",
    "The United States has a plan for a Zombie Apocalypse (CONPLAN 8888), written by junior officers as a training exercise but kept as an actual contingency.",
];