export const historicalFacts = [
    "The Great Pyramid of Giza was originally covered in highly polished white limestone casing stones.",
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "Oxford University is older than the Aztec Empire.",
    "Woolly mammoths were still alive when the Great Pyramid of Giza was being built.",
    "The University of Al Quaraouiyine in Morocco is the oldest existing, and continually operating educational institution in the world, founded in 859 AD.",
    "There were active volcanoes on the moon when dinosaurs roamed the Earth.",
    "The last time the guillotine was used in France was the same year Star Wars: A New Hope came out (1977).",
    "Sharks are older than trees. Sharks have existed for about 400 million years, while trees appeared about 350 million years ago.",
    "The Roman Empire was not the largest empire in history; the Mongol Empire and the British Empire were larger.",
    "Hero of Alexandria invented a steam engine called the aeolipile in the 1st century AD, long before the Industrial Revolution.",
    "The first person to be convicted of speeding was going 8 mph.",
    "Napoleon Bonaparte was not actually short; he was average height for a Frenchman of his time.",
    "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
    "There are more public libraries in the US than McDonald's restaurants.",
    "The fax machine was invented in 1843, before the telephone.",
    "The Colossus of Rhodes was only standing for 54 years before it snapped at the knees during an earthquake.",
    "During World War II, a Great Dane named Juliana was awarded the Blue Cross Medal. She extinguished an incendiary bomb by peeing on it.",
    "Alexander the Great was accidentally buried alive. Scientists believe he suffered from Guillain-Barré syndrome.",
    "There were female gladiators in Ancient Rome.",
    "The Vikings were the first Europeans to discover America, half a millennium before Christopher Columbus.",
    "Ketchup was sold in the 1830s as medicine.",
    "Tug of war was an Olympic sport between 1900 and 1920.",
    "The Leaning Tower of Pisa was never straight; it started leaning during construction.",
    "Ice pops were invented by an 11-year-old by accident.",
    "The world's oldest known customer complaint letter was written in ancient Babylon around 1750 BC.",
    "From 1912 to 1948, art competitions were part of the Olympics.",
    "The Great Fire of London in 1666 destroyed 13,500 houses but only killed 6 people (officially).",
    "Ancient Egyptians used slab of stone as pillows.",
    "In 1386, a pig in France was executed by public hanging for the murder of a child.",
    "Human history's most successful pirate was a Chinese prostitute named Ching Shih.",
    "The 100 Years War actually lasted 116 years.",
    "Turkeys were once worshipped like gods by the Maya people.",
    "Paul Revere never shouted 'The British are coming!'",
    "The chainsaw was originally invented to aid in childbirth.",
    "Ancient Romans used urine to whiten their teeth.",
    "The shortest reigning monarch in history was Louis XIX of France, who was king for 20 minutes.",
    "Before alarm clocks, there were 'knocker-uppers' who were hired to tap on windows to wake people up.",
    "Albert Einstein was offered the presidency of Israel in 1952 but declined.",
    "The first computer programmer was a woman named Ada Lovelace.",
    "During the Cold War, the CIA spent millions trying to use cats as spies.",
    "The longest war in history lasted 335 years between the Netherlands and the Isles of Scilly, with no casualties.",
    "Potatoes were illegal in France between 1748 and 1772.",
    "The first webcam was created at Cambridge University to check the status of a coffee pot.",
    "Russia ran out of vodka celebrating the end of World War II.",
    "The Titanic's owners planned to build a second Titanic, but the project was scrapped.",
    "Julius Caesar was kidnapped by pirates and demanded they increase his ransom.",
    "The first video ever uploaded to YouTube was titled 'Me at the zoo'.",
    "The Wright brothers' first flight was shorter than the wingspan of a Boeing 747.",
    "A bear named Wojtek served in the Polish army during World War II.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "The first mobile phone call was made in 1973.",
    "The ancient city of Troy was real, not just a myth.",
    "Spartans used iron sticks as currency to discourage hoarding wealth.",
    "The first vending machine was invented in the first century AD and dispensed holy water.",
    "The longest time between two twins being born is 87 days.",
    "The entire world's population could fit inside Los Angeles.",
    "There are more lifeforms living on your skin than there are people on the planet.",
    "The unicorn is the national animal of Scotland.",
    "The first oranges weren't orange.",
    "High heels were originally worn by men.",
    "The hashtag symbol is technically called an octothorpe.",
    "The 1904 Olympic marathon winner rode in a car for part of the race.",
    "The British Empire was the largest empire in world history.",
    "The first animal in space was a dog named Laika.",
    "The printing press was invented by Johannes Gutenberg around 1440.",
    "The Magna Carta was signed in 1215.",
    "The Black Death killed an estimated 75-200 million people in Eurasia.",
    "The Renaissance began in Italy in the 14th century.",
    "The Industrial Revolution began in Great Britain in the late 18th century.",
    "The French Revolution began in 1789.",
    "World War I began in 1914 and ended in 1918.",
    "World War II began in 1939 and ended in 1945.",
    "The Berlin Wall fell in 1989.",
    "The internet was invented in the late 20th century.",
    "The first human heart transplant was performed in 1967.",
    "The first test tube baby was born in 1978.",
    "The human genome project was completed in 2003.",
    "The first iPhone was released in 2007.",
    "The Curiosity rover landed on Mars in 2012.",
    "The first photo of a black hole was released in 2019.",
    "The COVID-19 pandemic began in 2019.",
    "Queen Elizabeth II was the longest-reigning British monarch.",
    "The United Nations was founded in 1945.",
    "The European Union was established in 1993.",
    "The Soviet Union dissolved in 1991.",
    "Apartheid in South Africa ended in the early 1990s.",
    "The Civil Rights Act of 1964 outlawed discrimination in the US.",
    "Women gained the right to vote in the US in 1920.",
    "The first man in space was Yuri Gagarin in 1961.",
    "The Apollo 11 mission landed humans on the Moon in 1969.",
    "The Hubble Space Telescope was launched in 1990.",
    "The International Space Station has been continuously occupied since 2000.",
    "The first successful airplane flight was in 1903.",
    "The Model T Ford was introduced in 1908.",
    "Penicillin was discovered by Alexander Fleming in 1928.",
    "The structure of DNA was discovered in 1953.",
    "The polio vaccine was developed in the 1950s.",
    "The smallpox virus was eradicated in 1980.",
    "The theory of relativity was proposed by Albert Einstein.",
    "The theory of evolution was proposed by Charles Darwin.",
    "The Big Bang theory explains the origin of the universe.",
    "The periodic table of elements was created by Dmitri Mendeleev.",
    "The telephone was patented by Alexander Graham Bell.",
    "The light bulb was improved and commercialized by Thomas Edison.",
    "The phonograph was invented by Thomas Edison.",
    "The motion picture camera was developed in the late 19th century.",
    "The radio was developed in the late 19th and early 20th centuries.",
    "The television was developed in the early 20th century.",
    "The transistor was invented in 1947.",
    "The integrated circuit was invented in the late 1950s.",
    "The microprocessor was invented in the early 1970s.",
    "The personal computer revolution began in the 1970s.",
    "The World Wide Web was invented by Tim Berners-Lee in 1989.",
    "Google was founded in 1998.",
    "Facebook was founded in 2004.",
    "Twitter was founded in 2006.",
    "Bitcoin was created in 2009.",
    "The first artificial satellite, Sputnik 1, was launched in 1957.",
    "The Voyager probes were launched in 1977.",
    "The Mars Pathfinder mission landed on Mars in 1997.",
    "The Cassini-Huygens mission explored Saturn and its moons.",
    "The New Horizons mission flew by Pluto in 2015.",
    "The James Webb Space Telescope was launched in 2021.",
    "The Rosetta mission landed a probe on a comet in 2014.",
    "The Kepler space telescope discovered thousands of exoplanets.",
    "The LIGO observatory detected gravitational waves in 2015.",
    "The Higgs boson was discovered at CERN in 2012.",
    "The human population reached 8 billion in 2022.",
    "The Paris Agreement on climate change was signed in 2016.",
    "The Brexit referendum took place in 2016.",
    "The Arab Spring protests began in 2010.",
    "The Fukushima nuclear disaster occurred in 2011.",
    "The Deepwater Horizon oil spill occurred in 2010.",
    "The 9/11 attacks occurred in 2001.",
    "The 2008 financial crisis was a major global economic downturn.",
    "The Euro currency was introduced in 1999.",
    "The Panama Canal was completed in 1914.",
    "The Suez Canal was opened in 1869.",
    "The Trans-Siberian Railway was completed in 1916.",
    "The Golden Gate Bridge was opened in 1937.",
    "The Empire State Building was completed in 1931.",
    "The Burj Khalifa is the tallest building in the world.",
    "The Three Gorges Dam is the world's largest power station.",
    "The Large Hadron Collider is the world's largest particle accelerator.",
    "The International Space Station is the most expensive object ever built.",
    "The Great Wall of China is the longest man-made structure.",
    "The Amazon rainforest is the largest rainforest in the world.",
    "The Sahara Desert is the largest hot desert in the world.",
    "Mount Everest is the highest mountain in the world.",
    "The Mariana Trench is the deepest part of the ocean.",
    "The Nile River is traditionally considered the longest river in the world.",
    "The Amazon River is the largest river by discharge volume.",
    "Lake Baikal is the deepest and oldest freshwater lake in the world.",
    "The Caspian Sea is the world's largest inland body of water.",
    "Greenland is the world's largest island.",
    "Australia is the smallest continent.",
    "Asia is the largest continent.",
    "The Pacific Ocean is the largest ocean.",
    "The Vatican City is the smallest country in the world.",
    "Russia is the largest country in the world by area.",
    "China is the most populous country in the world (or India, depending on recent data).",
    "Tokyo is the most populous metropolitan area in the world.",
    "English is the most widely spoken language in the world.",
    "Mandarin Chinese has the most native speakers.",
    "Christianity is the largest religion in the world.",
    "Islam is the second-largest religion in the world.",
    "Hinduism is the third-largest religion in the world.",
    "Buddhism is the fourth-largest religion in the world.",
    "The Bible is the best-selling book of all time.",
    "The Quran is the central religious text of Islam.",
    "The Torah is the central reference of the religious Judaic tradition.",
    "The Vedas are the oldest scriptures of Hinduism.",
    "The Tripitaka is the traditional term for the Buddhist scriptures.",
    "The Mona Lisa is the most famous painting in the world.",
    "The Starry Night is a famous painting by Vincent van Gogh.",
    "The Scream is a famous painting by Edvard Munch.",
    "Guernica is a famous painting by Pablo Picasso.",
    "The Last Supper is a famous mural painting by Leonardo da Vinci.",
    "The Sistine Chapel ceiling was painted by Michelangelo.",
    "The Statue of Liberty was a gift from France to the US.",
    "The Taj Mahal was built by Shah Jahan in memory of his wife.",
    "Machu Picchu is an Incan citadel in Peru.",
    "Petra is a historical and archaeological city in Jordan.",
    "Chichen Itza was a large pre-Columbian city built by the Maya people.",
    "The Colosseum is an oval amphitheatre in the centre of Rome.",
    "The Acropolis of Athens is an ancient citadel located on a rocky outcrop.",
    "Stonehenge is a prehistoric monument in England.",
    "The Terracotta Army is a collection of terracotta sculptures depicting the armies of Qin Shi Huang.",
    "The Forbidden City was the Chinese imperial palace from the Ming dynasty to the end of the Qing dynasty.",
    "The Palace of Versailles was the principal royal residence of France from 1682 to 1789.",
    "The White House is the official residence and workplace of the president of the United States.",
    "Buckingham Palace is the London residence and administrative headquarters of the monarch of the United Kingdom.",
    "The Kremlin is a fortified complex in the center of Moscow.",
    "The Pentagon is the headquarters of the United States Department of Defense.",
    "The Sydney Opera House is a multi-venue performing arts centre in Sydney.",
    "The Louvre is the world's largest art museum.",
    "The British Museum is dedicated to human history, art and culture.",
    "The Smithsonian Institution is the world's largest museum, education, and research complex.",
    "The Metropolitan Museum of Art is the largest art museum in the United States.",
    "The Nobel Prize is a set of annual international awards.",
    "The Academy Awards (Oscars) are awards for artistic and technical merit in the film industry.",
    "The Grammy Awards are awards presented by the Recording Academy to recognize outstanding achievement in the music industry.",
    "The Pulitzer Prize is an award for achievements in newspaper, magazine and online journalism, literature and musical composition.",
    "The Olympic Games are leading international sporting events.",
    "The FIFA World Cup is an international association football competition.",
    "The Super Bowl is the annual championship game of the National Football League.",
    "The Tour de France is an annual men's multiple-stage bicycle race.",
    "Wimbledon is the oldest tennis tournament in the world.",
    "The Masters Tournament is one of the four major championships in professional golf.",
    "The Kentucky Derby is a horse race held annually in Louisville, Kentucky.",
    "The Indianapolis 500 is an automobile race held annually at Indianapolis Motor Speedway.",
    "The Monaco Grand Prix is a Formula One motor race held annually on the Circuit de Monaco.",
    "The 24 Hours of Le Mans is the world's oldest active sports car race in endurance racing.",
];
